#!/usr/bin/env bash
# Installs and configures HAproxy on a server and configures HAproxy to:
# Distribute requests using roundrobin algorithm
# be manageable via an init script.


apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*
#Enabling HAprxoy to be started by the init script.
echo "ENABLED=1" >> /etc/default/haproxy

#Move the default configuratin file and create a new one.
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen load_b_hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 22-web-01 34.73.36.236:80 check
    server 22-web-02 35.231.173.232:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start