#!/usr/bin/env bash
#Configures nginx to listen on port 80 then stops nginx.
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
service nginx restart
kill -9  "$(pgrep 'nginx'|head -1)"
